SBV2_DIR: YOUR_SBV2_DIR
SBV2_VENV_DIR: YOUR_SBV2_VENV_DIR
VTUBE_STUDIO_SHORTCUT_PATH: YOUR_VTUBE_STUDIO_SHORTCUT_PATH
OBS_SHORTCUT_PATH: YOUR_OBS_SHORTCUT_PATH
OBS_IP: YOUR_OBS_IP # OBS StudioのIPアドレス
OBS_PORT: YOUR_OBS_PORT # OBS Studioのポート
OBS_PASSWORD: YOUR_OBS_PASSWORD # OBS Studioのパスワード
